create or replace function public.seed_starter_texts()
returns jsonb
language plpgsql
security invoker
as $$
declare
  v_family uuid := public.current_family_id();
  v_course uuid;
  v_source uuid;
  v_inserted_texts int := 0;
  v_total_texts int := 0;
begin
  if v_family is null then
    raise exception 'Sign in as a parent before running select public.seed_starter_texts();';
  end if;

  insert into public.courses (family_id, title, description)
  select v_family, 'Starter Texts Pre-A1', 'Idempotent Pre-A1 reading and listening text pack'
  where not exists (
    select 1 from public.courses where family_id = v_family and title = 'Starter Texts Pre-A1'
  );
  select id into v_course from public.courses where family_id = v_family and title = 'Starter Texts Pre-A1' limit 1;

  insert into public.sources (family_id, course_id, title, kind)
  select v_family, v_course, 'Starter texts generated seed', 'seed'
  where not exists (
    select 1 from public.sources where family_id = v_family and title = 'Starter texts generated seed'
  );
  select id into v_source from public.sources where family_id = v_family and title = 'Starter texts generated seed' limit 1;

  with seed_texts(position, title_en, title_ru, text_en, text_ru, topic, level, difficulty, tags, vocabulary_words, grammar_focus, comprehension_questions) as (
  values
    (1, 'My family', 'Моя семья', 'This is my family. I have got a mum, a dad and a sister. My mum is kind. My dad can run. I like my family.', 'Это моя семья. У меня есть мама, папа и сестра. Моя мама добрая. Мой папа умеет бегать. Я люблю свою семью.', 'family', 'pre_a1', 1, '["family","pre_a1"]'::jsonb, '[{"english":"family","russian":"семья"},{"english":"mum","russian":"мама"},{"english":"dad","russian":"папа"},{"english":"sister","russian":"сестра"}]'::jsonb, '["this is","have got","can","like"]'::jsonb, '[{"type":"choose_answer","question":"Who is in the family?","correctAnswer":"a mum, a dad and a sister","options":["a mum, a dad and a sister","two cats","a teacher"]},{"type":"true_false","question":"My mum is kind.","correctAnswer":"True","options":["True","False"]},{"type":"match_word_translation","question":"family","correctAnswer":"семья","options":["семья","школа","яблоко"]}]'::jsonb),
    (2, 'My school bag', 'Мой школьный портфель', 'I have got a school bag. It is blue. There is a book in my bag. There are two pencils. I like my bag.', 'У меня есть школьный портфель. Он синий. В моем портфеле есть книга. Там два карандаша. Мне нравится мой портфель.', 'school', 'pre_a1', 1, '["school","pre_a1"]'::jsonb, '[{"english":"school bag","russian":"школьный портфель"},{"english":"blue","russian":"синий"},{"english":"book","russian":"книга"},{"english":"pencil","russian":"карандаш"}]'::jsonb, '["have got","there is","there are","like"]'::jsonb, '[{"type":"choose_answer","question":"What colour is the bag?","correctAnswer":"blue","options":["blue","red","green"]},{"type":"true_false","question":"There are two pencils.","correctAnswer":"True","options":["True","False"]},{"type":"build_sentence_from_text","question":"Put the words in order.","prompt":"There is a book in my bag.","correctAnswer":"There is a book in my bag","options":["There","is","a","book","in","my","bag"]}]'::jsonb),
    (3, 'My cat', 'Моя кошка', 'I have got a cat. The cat is black. The cat is funny. It likes milk. I like my cat.', 'У меня есть кошка. Кошка черная. Кошка смешная. Она любит молоко. Я люблю свою кошку.', 'animals', 'pre_a1', 1, '["animals","pre_a1"]'::jsonb, '[{"english":"cat","russian":"кошка"},{"english":"black","russian":"черный"},{"english":"funny","russian":"смешной"},{"english":"milk","russian":"молоко"}]'::jsonb, '["have got","articles a/the","like"]'::jsonb, '[{"type":"choose_answer","question":"What has the child got?","correctAnswer":"a cat","options":["a cat","a dog","a fish"]},{"type":"choose_answer","question":"What colour is the cat?","correctAnswer":"black","options":["black","red","white"]},{"type":"choose_answer","question":"What does the cat like?","correctAnswer":"milk","options":["milk","tea","juice"]}]'::jsonb),
    (4, 'My dog', 'Моя собака', 'I have got a dog. My dog is big. It can run and jump. It has got a ball. My dog is happy.', 'У меня есть собака. Моя собака большая. Она умеет бегать и прыгать. У нее есть мяч. Моя собака счастливая.', 'animals', 'pre_a1', 1, '["animals","pre_a1"]'::jsonb, '[{"english":"dog","russian":"собака"},{"english":"big","russian":"большой"},{"english":"run","russian":"бегать"},{"english":"jump","russian":"прыгать"}]'::jsonb, '["have got","can","adjectives"]'::jsonb, '[{"type":"true_false","question":"The dog is big.","correctAnswer":"True","options":["True","False"]},{"type":"choose_answer","question":"What can the dog do?","correctAnswer":"run and jump","options":["run and jump","read and write","drink tea"]},{"type":"match_word_translation","question":"happy","correctAnswer":"счастливый","options":["счастливый","грустный","холодный"]}]'::jsonb),
    (5, 'My room', 'Моя комната', 'This is my room. There is a bed in my room. There is a table next to the bed. My lamp is yellow. I like my room.', 'Это моя комната. В моей комнате есть кровать. Рядом с кроватью есть стол. Моя лампа желтая. Мне нравится моя комната.', 'house', 'pre_a1', 1, '["house","pre_a1"]'::jsonb, '[{"english":"room","russian":"комната"},{"english":"bed","russian":"кровать"},{"english":"table","russian":"стол"},{"english":"lamp","russian":"лампа"}]'::jsonb, '["this is","there is","prepositions","like"]'::jsonb, '[{"type":"choose_answer","question":"What is in the room?","correctAnswer":"a bed","options":["a bed","a cat","a sandwich"]},{"type":"true_false","question":"The lamp is yellow.","correctAnswer":"True","options":["True","False"]},{"type":"build_sentence_from_text","question":"Put the words in order.","prompt":"This is my room.","correctAnswer":"This is my room","options":["This","is","my","room"]}]'::jsonb),
    (6, 'At school', 'В школе', 'I go to school on Monday. I have an English lesson. My teacher says, Listen and repeat. I open my book. I can read.', 'Я иду в школу в понедельник. У меня урок английского. Учитель говорит: слушай и повторяй. Я открываю книгу. Я умею читать.', 'school routine', 'pre_a1', 2, '["school routine","pre_a1"]'::jsonb, '[{"english":"school","russian":"школа"},{"english":"lesson","russian":"урок"},{"english":"teacher","russian":"учитель"},{"english":"read","russian":"читать"}]'::jsonb, '["present simple routine","classroom commands","can"]'::jsonb, '[{"type":"choose_answer","question":"What lesson has the child got?","correctAnswer":"an English lesson","options":["an English lesson","a music lesson","a tennis lesson"]},{"type":"true_false","question":"The teacher says, Listen and repeat.","correctAnswer":"True","options":["True","False"]},{"type":"match_word_translation","question":"teacher","correctAnswer":"учитель","options":["учитель","портфель","парк"]}]'::jsonb),
    (7, 'My lunch', 'Мой обед', 'I have got a sandwich. I have got an apple. The apple is red. I would like some juice. My lunch is good.', 'У меня есть бутерброд. У меня есть яблоко. Яблоко красное. Я бы хотел немного сока. Мой обед хороший.', 'food and drinks', 'pre_a1', 1, '["food and drinks","pre_a1"]'::jsonb, '[{"english":"sandwich","russian":"бутерброд"},{"english":"apple","russian":"яблоко"},{"english":"juice","russian":"сок"},{"english":"lunch","russian":"обед"}]'::jsonb, '["have got","articles a/an/the","would like"]'::jsonb, '[{"type":"choose_answer","question":"What colour is the apple?","correctAnswer":"red","options":["red","blue","black"]},{"type":"true_false","question":"The child would like some juice.","correctAnswer":"True","options":["True","False"]},{"type":"vocabulary_review_from_text","question":"apple","correctAnswer":"яблоко","options":["яблоко","молоко","карандаш"]}]'::jsonb),
    (8, 'My day', 'Мой день', 'I get up in the morning. I go to school. I read and write. In the evening I do my homework. Then I sleep.', 'Я встаю утром. Я иду в школу. Я читаю и пишу. Вечером я делаю домашнее задание. Потом я сплю.', 'time and daily routine', 'pre_a1', 2, '["time and daily routine","pre_a1"]'::jsonb, '[{"english":"morning","russian":"утро"},{"english":"go to school","russian":"ходить в школу"},{"english":"homework","russian":"домашнее задание"},{"english":"sleep","russian":"спать"}]'::jsonb, '["present simple routine","actions"]'::jsonb, '[{"type":"true_false","question":"The child goes to school.","correctAnswer":"True","options":["True","False"]},{"type":"choose_answer","question":"What does the child do in the evening?","correctAnswer":"homework","options":["homework","basketball","tea"]},{"type":"build_sentence_from_text","question":"Put the words in order.","prompt":"I go to school.","correctAnswer":"I go to school","options":["I","go","to","school"]}]'::jsonb),
    (9, 'The weather', 'Погода', 'It is sunny today. The sun is yellow. It is warm. I can play in the park. I am happy.', 'Сегодня солнечно. Солнце желтое. Тепло. Я могу играть в парке. Я счастлив.', 'weather', 'pre_a1', 1, '["weather","pre_a1"]'::jsonb, '[{"english":"sunny","russian":"солнечный"},{"english":"sun","russian":"солнце"},{"english":"warm","russian":"теплый"},{"english":"park","russian":"парк"}]'::jsonb, '["to be","articles the","can"]'::jsonb, '[{"type":"choose_answer","question":"What is the weather like?","correctAnswer":"sunny","options":["sunny","rainy","snowy"]},{"type":"true_false","question":"The child can play in the park.","correctAnswer":"True","options":["True","False"]},{"type":"match_word_translation","question":"warm","correctAnswer":"теплый","options":["теплый","холодный","серый"]}]'::jsonb),
    (10, 'In the park', 'В парке', 'I am in the park. There are two trees. I can see a bird. My friend can ride a bike. We like the park.', 'Я в парке. Там два дерева. Я вижу птицу. Мой друг умеет кататься на велосипеде. Нам нравится парк.', 'park', 'pre_a1', 2, '["park","pre_a1"]'::jsonb, '[{"english":"park","russian":"парк"},{"english":"tree","russian":"дерево"},{"english":"bird","russian":"птица"},{"english":"ride a bike","russian":"кататься на велосипеде"}]'::jsonb, '["there are","can","articles a/the","like"]'::jsonb, '[{"type":"choose_answer","question":"How many trees are there?","correctAnswer":"two","options":["two","one","ten"]},{"type":"true_false","question":"The friend can ride a bike.","correctAnswer":"True","options":["True","False"]},{"type":"match_word_translation","question":"bird","correctAnswer":"птица","options":["птица","рыба","кровать"]}]'::jsonb),
    (11, 'Would you like some juice?', 'Хотите сока?', 'Mum says, Would you like some juice? I say, Yes, please. The juice is orange. My sister says, No, thank you. She would like some water.', 'Мама говорит: хочешь немного сока? Я говорю: да, пожалуйста. Сок оранжевый. Моя сестра говорит: нет, спасибо. Она хотела бы немного воды.', 'polite requests', 'pre_a1', 2, '["polite requests","pre_a1"]'::jsonb, '[{"english":"juice","russian":"сок"},{"english":"Yes, please.","russian":"Да, пожалуйста."},{"english":"No, thank you.","russian":"Нет, спасибо."},{"english":"water","russian":"вода"}]'::jsonb, '["would like","polite requests","articles the"]'::jsonb, '[{"type":"choose_answer","question":"What does the child say?","correctAnswer":"Yes, please.","options":["Yes, please.","No, thank you.","I can swim."]},{"type":"true_false","question":"The sister would like some water.","correctAnswer":"True","options":["True","False"]},{"type":"vocabulary_review_from_text","question":"No, thank you.","correctAnswer":"Нет, спасибо.","options":["Нет, спасибо.","Да, пожалуйста.","Доброе утро."]}]'::jsonb),
    (12, 'My toys', 'Мои игрушки', 'I have got many toys. I have got a ball and a car. The ball is red. The car is small. I can play with my toys.', 'У меня много игрушек. У меня есть мяч и машинка. Мяч красный. Машинка маленькая. Я могу играть со своими игрушками.', 'toys', 'pre_a1', 1, '["toys","pre_a1"]'::jsonb, '[{"english":"toy","russian":"игрушка"},{"english":"ball","russian":"мяч"},{"english":"car","russian":"машинка"},{"english":"small","russian":"маленький"}]'::jsonb, '["have got","articles a/the","can"]'::jsonb, '[{"type":"choose_answer","question":"What toys has the child got?","correctAnswer":"a ball and a car","options":["a ball and a car","a cat and a dog","a book and a pen"]},{"type":"true_false","question":"The car is small.","correctAnswer":"True","options":["True","False"]},{"type":"match_word_translation","question":"small","correctAnswer":"маленький","options":["маленький","большой","веселый"]}]'::jsonb),
    (13, 'My clothes', 'Моя одежда', 'I have got a T-shirt. It is green. I have got blue trousers. My shoes are black. I put on my jacket.', 'У меня есть футболка. Она зеленая. У меня есть синие брюки. Мои ботинки черные. Я надеваю куртку.', 'clothes', 'pre_a1', 2, '["clothes","pre_a1"]'::jsonb, '[{"english":"T-shirt","russian":"футболка"},{"english":"trousers","russian":"брюки"},{"english":"shoes","russian":"ботинки"},{"english":"jacket","russian":"куртка"}]'::jsonb, '["have got","to be","colours"]'::jsonb, '[{"type":"choose_answer","question":"What colour is the T-shirt?","correctAnswer":"green","options":["green","yellow","pink"]},{"type":"true_false","question":"The shoes are black.","correctAnswer":"True","options":["True","False"]},{"type":"vocabulary_review_from_text","question":"trousers","correctAnswer":"брюки","options":["брюки","сок","окно"]}]'::jsonb),
    (14, 'My weekend', 'Мои выходные', 'It is Saturday. I am at home. I read a book and draw a picture. Then I play football in the park. I like my weekend.', 'Сегодня суббота. Я дома. Я читаю книгу и рисую картинку. Потом я играю в футбол в парке. Мне нравятся мои выходные.', 'weekend', 'pre_a1', 2, '["weekend","pre_a1"]'::jsonb, '[{"english":"Saturday","russian":"суббота"},{"english":"home","russian":"дом"},{"english":"draw a picture","russian":"рисовать картинку"},{"english":"play football","russian":"играть в футбол"}]'::jsonb, '["to be","present simple routine","like"]'::jsonb, '[{"type":"choose_answer","question":"What day is it?","correctAnswer":"Saturday","options":["Saturday","Monday","Friday"]},{"type":"true_false","question":"The child plays football in the park.","correctAnswer":"True","options":["True","False"]},{"type":"build_sentence_from_text","question":"Put the words in order.","prompt":"I read a book.","correctAnswer":"I read a book","options":["I","read","a","book"]}]'::jsonb),
    (15, 'My classroom', 'Мой класс', 'This is my classroom. There is a board on the wall. There are desks and chairs. The teacher is in the classroom. Open the book, please.', 'Это мой класс. На стене есть доска. Там есть парты и стулья. Учитель в классе. Открой книгу, пожалуйста.', 'classroom', 'pre_a1', 1, '["classroom","pre_a1"]'::jsonb, '[{"english":"classroom","russian":"класс"},{"english":"board","russian":"доска"},{"english":"desk","russian":"парта"},{"english":"chair","russian":"стул"}]'::jsonb, '["this is","there is","there are","classroom commands"]'::jsonb, '[{"type":"choose_answer","question":"Where is the board?","correctAnswer":"on the wall","options":["on the wall","under the chair","in the bag"]},{"type":"true_false","question":"The teacher is in the classroom.","correctAnswer":"True","options":["True","False"]},{"type":"match_word_translation","question":"board","correctAnswer":"доска","options":["доска","дверь","суп"]}]'::jsonb)
  )
  insert into public.topics (family_id, course_id, title)
  select distinct v_family, v_course, topic
  from seed_texts
  where not exists (
    select 1 from public.topics t where t.family_id = v_family and t.course_id = v_course and t.title = seed_texts.topic
  );

  with seed_texts(position, title_en, title_ru, text_en, text_ru, topic, level, difficulty, tags, vocabulary_words, grammar_focus, comprehension_questions) as (
  values
    (1, 'My family', 'Моя семья', 'This is my family. I have got a mum, a dad and a sister. My mum is kind. My dad can run. I like my family.', 'Это моя семья. У меня есть мама, папа и сестра. Моя мама добрая. Мой папа умеет бегать. Я люблю свою семью.', 'family', 'pre_a1', 1, '["family","pre_a1"]'::jsonb, '[{"english":"family","russian":"семья"},{"english":"mum","russian":"мама"},{"english":"dad","russian":"папа"},{"english":"sister","russian":"сестра"}]'::jsonb, '["this is","have got","can","like"]'::jsonb, '[{"type":"choose_answer","question":"Who is in the family?","correctAnswer":"a mum, a dad and a sister","options":["a mum, a dad and a sister","two cats","a teacher"]},{"type":"true_false","question":"My mum is kind.","correctAnswer":"True","options":["True","False"]},{"type":"match_word_translation","question":"family","correctAnswer":"семья","options":["семья","школа","яблоко"]}]'::jsonb),
    (2, 'My school bag', 'Мой школьный портфель', 'I have got a school bag. It is blue. There is a book in my bag. There are two pencils. I like my bag.', 'У меня есть школьный портфель. Он синий. В моем портфеле есть книга. Там два карандаша. Мне нравится мой портфель.', 'school', 'pre_a1', 1, '["school","pre_a1"]'::jsonb, '[{"english":"school bag","russian":"школьный портфель"},{"english":"blue","russian":"синий"},{"english":"book","russian":"книга"},{"english":"pencil","russian":"карандаш"}]'::jsonb, '["have got","there is","there are","like"]'::jsonb, '[{"type":"choose_answer","question":"What colour is the bag?","correctAnswer":"blue","options":["blue","red","green"]},{"type":"true_false","question":"There are two pencils.","correctAnswer":"True","options":["True","False"]},{"type":"build_sentence_from_text","question":"Put the words in order.","prompt":"There is a book in my bag.","correctAnswer":"There is a book in my bag","options":["There","is","a","book","in","my","bag"]}]'::jsonb),
    (3, 'My cat', 'Моя кошка', 'I have got a cat. The cat is black. The cat is funny. It likes milk. I like my cat.', 'У меня есть кошка. Кошка черная. Кошка смешная. Она любит молоко. Я люблю свою кошку.', 'animals', 'pre_a1', 1, '["animals","pre_a1"]'::jsonb, '[{"english":"cat","russian":"кошка"},{"english":"black","russian":"черный"},{"english":"funny","russian":"смешной"},{"english":"milk","russian":"молоко"}]'::jsonb, '["have got","articles a/the","like"]'::jsonb, '[{"type":"choose_answer","question":"What has the child got?","correctAnswer":"a cat","options":["a cat","a dog","a fish"]},{"type":"choose_answer","question":"What colour is the cat?","correctAnswer":"black","options":["black","red","white"]},{"type":"choose_answer","question":"What does the cat like?","correctAnswer":"milk","options":["milk","tea","juice"]}]'::jsonb),
    (4, 'My dog', 'Моя собака', 'I have got a dog. My dog is big. It can run and jump. It has got a ball. My dog is happy.', 'У меня есть собака. Моя собака большая. Она умеет бегать и прыгать. У нее есть мяч. Моя собака счастливая.', 'animals', 'pre_a1', 1, '["animals","pre_a1"]'::jsonb, '[{"english":"dog","russian":"собака"},{"english":"big","russian":"большой"},{"english":"run","russian":"бегать"},{"english":"jump","russian":"прыгать"}]'::jsonb, '["have got","can","adjectives"]'::jsonb, '[{"type":"true_false","question":"The dog is big.","correctAnswer":"True","options":["True","False"]},{"type":"choose_answer","question":"What can the dog do?","correctAnswer":"run and jump","options":["run and jump","read and write","drink tea"]},{"type":"match_word_translation","question":"happy","correctAnswer":"счастливый","options":["счастливый","грустный","холодный"]}]'::jsonb),
    (5, 'My room', 'Моя комната', 'This is my room. There is a bed in my room. There is a table next to the bed. My lamp is yellow. I like my room.', 'Это моя комната. В моей комнате есть кровать. Рядом с кроватью есть стол. Моя лампа желтая. Мне нравится моя комната.', 'house', 'pre_a1', 1, '["house","pre_a1"]'::jsonb, '[{"english":"room","russian":"комната"},{"english":"bed","russian":"кровать"},{"english":"table","russian":"стол"},{"english":"lamp","russian":"лампа"}]'::jsonb, '["this is","there is","prepositions","like"]'::jsonb, '[{"type":"choose_answer","question":"What is in the room?","correctAnswer":"a bed","options":["a bed","a cat","a sandwich"]},{"type":"true_false","question":"The lamp is yellow.","correctAnswer":"True","options":["True","False"]},{"type":"build_sentence_from_text","question":"Put the words in order.","prompt":"This is my room.","correctAnswer":"This is my room","options":["This","is","my","room"]}]'::jsonb),
    (6, 'At school', 'В школе', 'I go to school on Monday. I have an English lesson. My teacher says, Listen and repeat. I open my book. I can read.', 'Я иду в школу в понедельник. У меня урок английского. Учитель говорит: слушай и повторяй. Я открываю книгу. Я умею читать.', 'school routine', 'pre_a1', 2, '["school routine","pre_a1"]'::jsonb, '[{"english":"school","russian":"школа"},{"english":"lesson","russian":"урок"},{"english":"teacher","russian":"учитель"},{"english":"read","russian":"читать"}]'::jsonb, '["present simple routine","classroom commands","can"]'::jsonb, '[{"type":"choose_answer","question":"What lesson has the child got?","correctAnswer":"an English lesson","options":["an English lesson","a music lesson","a tennis lesson"]},{"type":"true_false","question":"The teacher says, Listen and repeat.","correctAnswer":"True","options":["True","False"]},{"type":"match_word_translation","question":"teacher","correctAnswer":"учитель","options":["учитель","портфель","парк"]}]'::jsonb),
    (7, 'My lunch', 'Мой обед', 'I have got a sandwich. I have got an apple. The apple is red. I would like some juice. My lunch is good.', 'У меня есть бутерброд. У меня есть яблоко. Яблоко красное. Я бы хотел немного сока. Мой обед хороший.', 'food and drinks', 'pre_a1', 1, '["food and drinks","pre_a1"]'::jsonb, '[{"english":"sandwich","russian":"бутерброд"},{"english":"apple","russian":"яблоко"},{"english":"juice","russian":"сок"},{"english":"lunch","russian":"обед"}]'::jsonb, '["have got","articles a/an/the","would like"]'::jsonb, '[{"type":"choose_answer","question":"What colour is the apple?","correctAnswer":"red","options":["red","blue","black"]},{"type":"true_false","question":"The child would like some juice.","correctAnswer":"True","options":["True","False"]},{"type":"vocabulary_review_from_text","question":"apple","correctAnswer":"яблоко","options":["яблоко","молоко","карандаш"]}]'::jsonb),
    (8, 'My day', 'Мой день', 'I get up in the morning. I go to school. I read and write. In the evening I do my homework. Then I sleep.', 'Я встаю утром. Я иду в школу. Я читаю и пишу. Вечером я делаю домашнее задание. Потом я сплю.', 'time and daily routine', 'pre_a1', 2, '["time and daily routine","pre_a1"]'::jsonb, '[{"english":"morning","russian":"утро"},{"english":"go to school","russian":"ходить в школу"},{"english":"homework","russian":"домашнее задание"},{"english":"sleep","russian":"спать"}]'::jsonb, '["present simple routine","actions"]'::jsonb, '[{"type":"true_false","question":"The child goes to school.","correctAnswer":"True","options":["True","False"]},{"type":"choose_answer","question":"What does the child do in the evening?","correctAnswer":"homework","options":["homework","basketball","tea"]},{"type":"build_sentence_from_text","question":"Put the words in order.","prompt":"I go to school.","correctAnswer":"I go to school","options":["I","go","to","school"]}]'::jsonb),
    (9, 'The weather', 'Погода', 'It is sunny today. The sun is yellow. It is warm. I can play in the park. I am happy.', 'Сегодня солнечно. Солнце желтое. Тепло. Я могу играть в парке. Я счастлив.', 'weather', 'pre_a1', 1, '["weather","pre_a1"]'::jsonb, '[{"english":"sunny","russian":"солнечный"},{"english":"sun","russian":"солнце"},{"english":"warm","russian":"теплый"},{"english":"park","russian":"парк"}]'::jsonb, '["to be","articles the","can"]'::jsonb, '[{"type":"choose_answer","question":"What is the weather like?","correctAnswer":"sunny","options":["sunny","rainy","snowy"]},{"type":"true_false","question":"The child can play in the park.","correctAnswer":"True","options":["True","False"]},{"type":"match_word_translation","question":"warm","correctAnswer":"теплый","options":["теплый","холодный","серый"]}]'::jsonb),
    (10, 'In the park', 'В парке', 'I am in the park. There are two trees. I can see a bird. My friend can ride a bike. We like the park.', 'Я в парке. Там два дерева. Я вижу птицу. Мой друг умеет кататься на велосипеде. Нам нравится парк.', 'park', 'pre_a1', 2, '["park","pre_a1"]'::jsonb, '[{"english":"park","russian":"парк"},{"english":"tree","russian":"дерево"},{"english":"bird","russian":"птица"},{"english":"ride a bike","russian":"кататься на велосипеде"}]'::jsonb, '["there are","can","articles a/the","like"]'::jsonb, '[{"type":"choose_answer","question":"How many trees are there?","correctAnswer":"two","options":["two","one","ten"]},{"type":"true_false","question":"The friend can ride a bike.","correctAnswer":"True","options":["True","False"]},{"type":"match_word_translation","question":"bird","correctAnswer":"птица","options":["птица","рыба","кровать"]}]'::jsonb),
    (11, 'Would you like some juice?', 'Хотите сока?', 'Mum says, Would you like some juice? I say, Yes, please. The juice is orange. My sister says, No, thank you. She would like some water.', 'Мама говорит: хочешь немного сока? Я говорю: да, пожалуйста. Сок оранжевый. Моя сестра говорит: нет, спасибо. Она хотела бы немного воды.', 'polite requests', 'pre_a1', 2, '["polite requests","pre_a1"]'::jsonb, '[{"english":"juice","russian":"сок"},{"english":"Yes, please.","russian":"Да, пожалуйста."},{"english":"No, thank you.","russian":"Нет, спасибо."},{"english":"water","russian":"вода"}]'::jsonb, '["would like","polite requests","articles the"]'::jsonb, '[{"type":"choose_answer","question":"What does the child say?","correctAnswer":"Yes, please.","options":["Yes, please.","No, thank you.","I can swim."]},{"type":"true_false","question":"The sister would like some water.","correctAnswer":"True","options":["True","False"]},{"type":"vocabulary_review_from_text","question":"No, thank you.","correctAnswer":"Нет, спасибо.","options":["Нет, спасибо.","Да, пожалуйста.","Доброе утро."]}]'::jsonb),
    (12, 'My toys', 'Мои игрушки', 'I have got many toys. I have got a ball and a car. The ball is red. The car is small. I can play with my toys.', 'У меня много игрушек. У меня есть мяч и машинка. Мяч красный. Машинка маленькая. Я могу играть со своими игрушками.', 'toys', 'pre_a1', 1, '["toys","pre_a1"]'::jsonb, '[{"english":"toy","russian":"игрушка"},{"english":"ball","russian":"мяч"},{"english":"car","russian":"машинка"},{"english":"small","russian":"маленький"}]'::jsonb, '["have got","articles a/the","can"]'::jsonb, '[{"type":"choose_answer","question":"What toys has the child got?","correctAnswer":"a ball and a car","options":["a ball and a car","a cat and a dog","a book and a pen"]},{"type":"true_false","question":"The car is small.","correctAnswer":"True","options":["True","False"]},{"type":"match_word_translation","question":"small","correctAnswer":"маленький","options":["маленький","большой","веселый"]}]'::jsonb),
    (13, 'My clothes', 'Моя одежда', 'I have got a T-shirt. It is green. I have got blue trousers. My shoes are black. I put on my jacket.', 'У меня есть футболка. Она зеленая. У меня есть синие брюки. Мои ботинки черные. Я надеваю куртку.', 'clothes', 'pre_a1', 2, '["clothes","pre_a1"]'::jsonb, '[{"english":"T-shirt","russian":"футболка"},{"english":"trousers","russian":"брюки"},{"english":"shoes","russian":"ботинки"},{"english":"jacket","russian":"куртка"}]'::jsonb, '["have got","to be","colours"]'::jsonb, '[{"type":"choose_answer","question":"What colour is the T-shirt?","correctAnswer":"green","options":["green","yellow","pink"]},{"type":"true_false","question":"The shoes are black.","correctAnswer":"True","options":["True","False"]},{"type":"vocabulary_review_from_text","question":"trousers","correctAnswer":"брюки","options":["брюки","сок","окно"]}]'::jsonb),
    (14, 'My weekend', 'Мои выходные', 'It is Saturday. I am at home. I read a book and draw a picture. Then I play football in the park. I like my weekend.', 'Сегодня суббота. Я дома. Я читаю книгу и рисую картинку. Потом я играю в футбол в парке. Мне нравятся мои выходные.', 'weekend', 'pre_a1', 2, '["weekend","pre_a1"]'::jsonb, '[{"english":"Saturday","russian":"суббота"},{"english":"home","russian":"дом"},{"english":"draw a picture","russian":"рисовать картинку"},{"english":"play football","russian":"играть в футбол"}]'::jsonb, '["to be","present simple routine","like"]'::jsonb, '[{"type":"choose_answer","question":"What day is it?","correctAnswer":"Saturday","options":["Saturday","Monday","Friday"]},{"type":"true_false","question":"The child plays football in the park.","correctAnswer":"True","options":["True","False"]},{"type":"build_sentence_from_text","question":"Put the words in order.","prompt":"I read a book.","correctAnswer":"I read a book","options":["I","read","a","book"]}]'::jsonb),
    (15, 'My classroom', 'Мой класс', 'This is my classroom. There is a board on the wall. There are desks and chairs. The teacher is in the classroom. Open the book, please.', 'Это мой класс. На стене есть доска. Там есть парты и стулья. Учитель в классе. Открой книгу, пожалуйста.', 'classroom', 'pre_a1', 1, '["classroom","pre_a1"]'::jsonb, '[{"english":"classroom","russian":"класс"},{"english":"board","russian":"доска"},{"english":"desk","russian":"парта"},{"english":"chair","russian":"стул"}]'::jsonb, '["this is","there is","there are","classroom commands"]'::jsonb, '[{"type":"choose_answer","question":"Where is the board?","correctAnswer":"on the wall","options":["on the wall","under the chair","in the bag"]},{"type":"true_false","question":"The teacher is in the classroom.","correctAnswer":"True","options":["True","False"]},{"type":"match_word_translation","question":"board","correctAnswer":"доска","options":["доска","дверь","суп"]}]'::jsonb)
  ),
  inserted as (
    insert into public.learning_texts (
      family_id, course_id, source_id, topic_id, title_en, title_ru, text_en, text_ru,
      level, difficulty, tags, vocabulary_words, grammar_focus, comprehension_questions, status, created_by
    )
    select
      v_family, v_course, v_source, t.id, s.title_en, s.title_ru, s.text_en, s.text_ru,
      s.level, s.difficulty, s.tags, s.vocabulary_words, s.grammar_focus, s.comprehension_questions,
      'active', auth.uid()
    from seed_texts s
    join public.topics t on t.family_id = v_family and t.course_id = v_course and t.title = s.topic
    where not exists (
      select 1
      from public.learning_texts existing
      where existing.family_id = v_family
        and existing.source_id = v_source
        and lower(existing.title_en) = lower(s.title_en)
    )
    returning id
  )
  select count(*) into v_inserted_texts from inserted;

  select count(*) into v_total_texts
  from public.learning_texts
  where family_id = v_family and source_id = v_source;

  return jsonb_build_object(
    'inserted_texts', v_inserted_texts,
    'existing_texts', greatest(v_total_texts - v_inserted_texts, 0),
    'total_texts', v_total_texts,
    'course_title', 'Starter Texts Pre-A1'
  );
end;
$$;
